# Generated by Django 4.2.13 on 2026-04-30 18:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voter_hash', models.CharField(max_length=64)),
                ('encrypted_payload', models.TextField()),
                ('cast_at', models.DateTimeField(auto_now_add=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='elections.election')),
            ],
            options={
                'db_table': 'votes',
                'indexes': [models.Index(fields=['election'], name='votes_electio_7d3e07_idx'), models.Index(fields=['voter_hash'], name='votes_voter_h_b3bede_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('voter_hash', 'election'), name='unique_voter_per_election'),
        ),
    ]
