# Generated by Django 5.1.1 on 2026-06-11 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='tx_hash',
            field=models.CharField(blank=True, help_text='Ballot Submission Transaction Hash on Blockchain', max_length=66, null=True),
        ),
    ]
