# Generated by Django 5.1.1 on 2026-04-30 22:37

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='bio',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='election',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Description'),
        ),
    ]
