# Generated by Django 5.1.1 on 2026-06-11 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_alter_candidate_bio_alter_election_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='contract_address',
            field=models.CharField(blank=True, help_text='Deployed Smart Contract Address on Ethereum Sepolia', max_length=42, null=True),
        ),
        migrations.AddField(
            model_name='election',
            name='tx_hash',
            field=models.CharField(blank=True, help_text='Contract Deployment Transaction Hash', max_length=66, null=True),
        ),
    ]
